plugins {
	id 'java'
	id 'org.springframework.boot' version '4.0.6'
	id 'io.spring.dependency-management' version '1.1.7'
}

group = 'edu.mx.tecdesoftware'
version = '0.0.1-SNAPSHOT'

java {
	toolchain {
		languageVersion = JavaLanguageVersion.of(21)
	}
}

repositories {
	mavenCentral()
}

dependencies {
	// Servidor web y API REST
	implementation 'org.springframework.boot:spring-boot-starter-web'

	// Conexión a Base de Datos (fíjate en el guion antes de jpa)
	implementation 'org.springframework.boot:spring-boot-starter-data-jpa'

	// Herramientas de testing estándar de Spring Boot
	testImplementation 'org.springframework.boot:spring-boot-starter-test'
	runtimeOnly 'org.postgresql:postgresql'
	testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

tasks.named('test') {
	useJUnitPlatform()
}
